version: '3'

services: 
  node-app:
    container_name: verify-node-app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 5050:5050
  
#  caddy:
#    image: caddy/caddy:2.4.3-alpine
#    container_name: caddy-service
#    restart: always
#    ports: 
#      - 80:80
#      - 443:443
#    volumes:
#      - $PWD/Caddyfile:/etc/caddy/Caddyfile
#      - $PWD/site:/srv
#      - caddy_data:/data
#      - caddy_config:/config
#    depends_on: 
#      - node-app

# volumes: 
#  caddy_data:
#  caddy_config:
